# How to use Metadata Editor

In [8]:
from pymetadataeditor import MetadataEditor
import os

## Examples of the interface

In [9]:
your_api_key = os.getenv("API_KEY")
api_url = os.getenv("API_URL")
me = MetadataEditor(api_url=api_url, api_key=your_api_key, verify_ssl=False)

### Listing your projects

In [10]:
me.list_projects().tail()

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,published,created,changed,varcount,created_by,changed_by,is_shared,thumbnail,template_uid,username,username_cr,collections
id,,,,,,,,,,,,,,,,,,,,
1396,timeseries,TM.TAX.TCOM.SR.ZS,None,"Share of tariff lines with specific rates, pri...",None,,0,0,None,2023-02-07T22:03:35+00:00,2023-02-07T22:03:35+00:00,None,2,2,None,None,None,Olivier Dupriez,Olivier Dupriez,"[{'id': '1', 'title': 'WDI', 'sid': '1396'}]"
1391,timeseries,TM.TAX.TCOM.BC.ZS,None,"Binding coverage, primary products (%)",None,,0,0,None,2023-02-07T22:03:34+00:00,2023-02-07T22:03:34+00:00,None,2,2,None,None,None,Olivier Dupriez,Olivier Dupriez,"[{'id': '1', 'title': 'WDI', 'sid': '1391'}]"
1392,timeseries,TM.TAX.TCOM.BR.ZS,None,"Bound rate, simple mean, primary products (%)",None,,0,0,None,2023-02-07T22:03:34+00:00,2023-02-07T22:03:34+00:00,None,2,2,None,None,None,Olivier Dupriez,Olivier Dupriez,"[{'id': '1', 'title': 'WDI', 'sid': '1392'}]"
1387,timeseries,TM.TAX.MRCH.SM.FN.ZS,None,"Tariff rate, most favored nation, simple mean,...",None,,0,0,None,2023-02-07T22:03:33+00:00,2023-02-07T22:03:33+00:00,None,2,2,None,None,None,Olivier Dupriez,Olivier Dupriez,"[{'id': '1', 'title': 'WDI', 'sid': '1387'}]"
1388,timeseries,TM.TAX.MRCH.SR.ZS,None,"Share of tariff lines with specific rates, all...",None,,0,0,None,2023-02-07T22:03:33+00:00,2023-02-07T22:03:33+00:00,None,2,2,None,None,None,Olivier Dupriez,Olivier Dupriez,"[{'id': '1', 'title': 'WDI', 'sid': '1388'}]"

### Creating a new timeseries project

In [15]:
series_description = {
                        "idno": "GB20240709_demo1",
                        "doi": "V1",
                        "name": "Version 1",
                        "display_name": "Version 1"
                     }

timeseries_id = me.create_project_log("timeseries", {"idno": "GB20240709_demo1", "series_description": series_description})

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [16]:
me.list_projects().sort_values("created").tail()

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,published,created,changed,varcount,created_by,changed_by,is_shared,thumbnail,template_uid,username,username_cr,collections
id,,,,,,,,,,,,,,,,,,,,
1598,script,ee56ce01-3aba-49f3-87dc-9ab44cae68a3,PP_ZAF_2022_PRWP-9345_v01,(DUPLICATE MOVED) Job Search and Hiring with L...,None,,0,0,None,2023-06-13T20:02:14+00:00,2023-07-07T16:11:32+00:00,None,13,13,None,thumbnail-1598.png,None,chriskrestel,chriskrestel,"[{'id': '4', 'title': 'REPRODUCIBILITY', 'sid'..."
1599,script,1f0520b2-89b3-41c9-af4d-fd9b023da50c,PP_ARG_2019_PRWP-7348_v01,(DUPLICATE MOVED) Long-Run Effects of Temporar...,None,,0,0,None,2023-06-14T14:02:02+00:00,2023-07-07T16:11:11+00:00,None,13,13,None,thumbnail-1599.png,None,chriskrestel,chriskrestel,"[{'id': '4', 'title': 'REPRODUCIBILITY', 'sid'..."
1600,script,2cd4ebed-4690-43d0-bcbd-2d7497d63fbd,PP_IND_2022_PRWP-9390_v01,(DUPLICATE MOVED) On the Quantity and Quality ...,None,,0,0,None,2023-06-14T14:33:19+00:00,2023-07-07T16:10:26+00:00,None,13,13,None,thumbnail-1600.png,None,chriskrestel,chriskrestel,"[{'id': '4', 'title': 'REPRODUCIBILITY', 'sid'..."
1607,script,464ea13d-a254-4eeb-9f46-bddec9ac4fcf,PP_ETH_2020_EXT-2_v01,(DUPLICATE-MOVED) Reproducibility package for ...,None,,0,0,None,2023-06-14T19:18:23+00:00,2023-06-26T19:23:26+00:00,None,13,13,None,thumbnail-1607.png,d0e54377885c64c360259b65398e319d,chriskrestel,chriskrestel,"[{'id': '4', 'title': 'REPRODUCIBILITY', 'sid'..."
2032,timeseries,GB20240709_demo1,GB20240709_demo1,Version 1,None,,0,0,None,2024-08-09T14:22:50+00:00,2024-08-09T14:22:50+00:00,None,24,24,None,None,8603d94e27bccc2bdad1e00dbbf0fe32en,Gordon Blackadder,Gordon Blackadder,[]

In [17]:
me.get_project_by_id(timeseries_id)

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

id                                                               2032
idno                                                 GB20240709_demo1
type                                                       timeseries
title                                                       Version 1
abbreviation                                                     None
authoring_entity                                                 None
nation
year_start                                                          0
year_end                                                            0
metafile                                                         None
dirpath                              5352696a9ca3397beb79f116f3a33991
varcount                                                         None
published                                                        None
created                                     2024-08-09T14:22:50+00:00
changed                                     2024-08-09T14:22:50+00:00
created_by                                                         24
changed_by                                                         24
thumbnail                                                        None
metadata            {'idno': 'GB20240709_demo1', 'series_descripti...
template_uid                       8603d94e27bccc2bdad1e00dbbf0fe32en
is_shared                                                        None
study_idno                                           GB20240709_demo1
dtype: object

In [18]:
me.get_project_metadata_by_id(timeseries_id, mode='dict')

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

{'idno': 'GB20240709_demo1',
 'series_description': {'idno': 'GB20240709_demo1',
  'doi': 'V1',
  'name': 'Version 1',
  'display_name': 'Version 1'}}

# Starting with outlines

The metadata can be both large and hierarchical. Starting with a skeleton outline makes things easier.

Outlines are available in three modes - dictionary, pydantic model and as an Excel file.

Dictionaries are created like so:

In [10]:
timeseries_dict = me.outline_metadata('timeseries', mode='dict')
timeseries_dict

{'idno': None,
 'metadata_information': {'title': None,
  'idno': None,
  'producers': [{'name': None,
    'abbr': None,
    'affiliation': None,
    'role': None}],
  'prod_date': None,
  'version_statement': {'version': None,
   'version_date': None,
   'version_resp': None,
   'version_notes': None}},
 'series_description': {'idno': '',
  'doi': None,
  'name': '',
  'display_name': None,
  'authoring_entity': [{'name': '',
    'affiliation': None,
    'abbreviation': '',
    'email': '',
    'uri': None}],
  'database_id': None,
  'database_name': None,
  'date_last_update': None,
  'date_released': None,
  'version_statement': {'version': None,
   'version_date': None,
   'version_resp': None,
   'version_notes': None},
  'aliases': [{'alias': None}],
  'alternate_identifiers': [{'identifier': '',
    'name': None,
    'database': None,
    'uri': None,
    'notes': None}],
  'languages': [{'name': None, 'code': None}],
  'measurement_unit': None,
  'power_code': None,
  'dimensions': [{'name': None, 'label': '', 'description': None}],
  'release_calendar': None,
  'periodicity': None,
  'base_period': None,
  'definition_short': None,
  'definition_long': None,
  'definition_references': [{'source': None, 'uri': '', 'note': None}],
  'statistical_concept': None,
  'statistical_concept_references': [{'source': None,
    'uri': '',
    'note': None}],
  'concepts': [{'name': '', 'definition': None, 'uri': None}],
  'universe': None,
  'data_collection': {'data_source': None,
   'method': None,
   'period': None,
   'note': None,
   'uri': None},
  'methodology': None,
  'methodology_references': [{'source': None, 'uri': '', 'note': None}],
  'derivation': None,
  'derivation_references': [{'source': None, 'uri': '', 'note': None}],
  'imputation': None,
  'imputation_references': [{'source': None, 'uri': '', 'note': None}],
  'seasonal_adjustment': None,
  'adjustments': [],
  'missing': None,
  'validation_rules': [],
  'quality_checks': None,
  'quality_note': None,
  'sources_discrepancies': None,
  'series_break': None,
  'limitation': None,
  'themes': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'topics': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'disciplines': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'relevance': None,
  'mandate': {'mandate': None, 'uri': None},
  'time_periods': [{'start': None, 'end': None, 'notes': None}],
  'ref_country': [{'name': None, 'code': None}],
  'geographic_units': [{'name': '', 'code': None, 'type': None}],
  'bbox': [{'west': None, 'east': None, 'south': None, 'north': None}],
  'aggregation_method': None,
  'aggregation_method_references': [{'source': None, 'uri': '', 'note': None}],
  'disaggregation': None,
  'license': [{'name': None, 'uri': None, 'note': None}],
  'confidentiality': None,
  'confidentiality_status': None,
  'confidentiality_note': None,
  'citation_requirement': None,
  'links': [{'type': None, 'description': None, 'uri': None}],
  'api_documentation': [{'description': None, 'uri': None}],
  'sources': [{'idno': None,
    'other_identifiers': [{'type': None, 'identifier': None}],
    'type': None,
    'name': '',
    'organization': None,
    'authors': [{'first_name': None,
      'initial': None,
      'last_name': None,
      'affiliation': None,
      'author_id': [{'type': None, 'id': None}],
      'full_name': None}],
    'datasets': [{'idno': None, 'title': None, 'uri': None}],
    'publisher': None,
    'publication_date': None,
    'uri': None,
    'access_date': None,
    'note': None}],
  'sources_note': None,
  'direct_sources': [{'name': None,
    'organization': None,
    'uri': None,
    'note': None}],
  'keywords': [{'name': '', 'vocabulary': None, 'uri': None}],
  'acronyms': [{'acronym': '', 'expansion': '', 'occurrence': None}],
  'errata': [{'date': None, 'description': None, 'uri': None}],
  'acknowledgements': [{'name': None, 'affiliation': None, 'role': None}],
  'acknowledgement_statement': None,
  'disclaimer': None,
  'notes': [{'note': None, 'type': None, 'uri': None}],
  'related_indicators': [{'code': None,
    'label': None,
    'uri': None,
    'relationship': None,
    'type': None}],
  'compliance': [{'standard': '',
    'abbreviation': None,
    'custodian': None,
    'uri': None}],
  'framework': [{'name': '',
    'abbreviation': None,
    'custodian': None,
    'description': None,
    'goal_id': None,
    'goal_name': None,
    'goal_description': None,
    'target_id': None,
    'target_name': None,
    'target_description': None,
    'indicator_id': None,
    'indicator_name': None,
    'indicator_description': None,
    'uri': None,
    'notes': None}],
  'series_groups': [{'name': None,
    'description': None,
    'version': None,
    'uri': None}],
  'contacts': [{'name': None,
    'role': None,
    'position': None,
    'affiliation': None,
    'email': None,
    'telephone': None,
    'uri': None}]},
 'data_structure': [{'name': None,
   'label': None,
   'description': None,
   'data_type': None,
   'column_type': None,
   'time_period_format': None,
   'code_list': [{'code': None, 'name': None, 'description': None}],
   'code_list_reference': {'id': None,
    'name': None,
    'version': None,
    'uri': '',
    'note': None}}],
 'data_notes': [{'filters': [{'field': None, 'operator': None, 'value': []}],
   'note': None}],
 'datacite': {'doi': None,
  'prefix': None,
  'suffix': None,
  'creators': [{'name': '',
    'nameType': None,
    'givenName': None,
    'familyName': None}],
  'titles': [{'title': '', 'titleType': None, 'lang': None}],
  'publisher': None,
  'publicationYear': None,
  'types': {'resourceType': '', 'resourceTypeGeneral': None},
  'url': None,
  'language': None},
 'provenance': [{'origin_description': {'harvest_date': None,
    'altered': None,
    'base_url': None,
    'identifier': None,
    'date_stamp': None,
    'metadata_namespace': None}}],
 'tags': [{'tag': None, 'tag_group': None}],
 'additional': {'': ''}}

and updated in the usual way:

In [12]:
timeseries_dict['metadata_information']['producers'][0]['name'] = "example_producer"
timeseries_dict

{'idno': None,
 'metadata_information': {'title': None,
  'idno': None,
  'producers': [{'name': 'example_producer',
    'abbr': None,
    'affiliation': None,
    'role': None}],
  'prod_date': None,
  'version_statement': {'version': None,
   'version_date': None,
   'version_resp': None,
   'version_notes': None}},
 'series_description': {'idno': '',
  'doi': None,
  'name': '',
  'display_name': None,
  'authoring_entity': [{'name': '',
    'affiliation': None,
    'abbreviation': '',
    'email': '',
    'uri': None}],
  'database_id': None,
  'database_name': None,
  'date_last_update': None,
  'date_released': None,
  'version_statement': {'version': None,
   'version_date': None,
   'version_resp': None,
   'version_notes': None},
  'aliases': [{'alias': None}],
  'alternate_identifiers': [{'identifier': '',
    'name': None,
    'database': None,
    'uri': None,
    'notes': None}],
  'languages': [{'name': None, 'code': None}],
  'measurement_unit': None,
  'power_code': None,
  'dimensions': [{'name': None, 'label': '', 'description': None}],
  'release_calendar': None,
  'periodicity': None,
  'base_period': None,
  'definition_short': None,
  'definition_long': None,
  'definition_references': [{'source': None, 'uri': '', 'note': None}],
  'statistical_concept': None,
  'statistical_concept_references': [{'source': None,
    'uri': '',
    'note': None}],
  'concepts': [{'name': '', 'definition': None, 'uri': None}],
  'universe': None,
  'data_collection': {'data_source': None,
   'method': None,
   'period': None,
   'note': None,
   'uri': None},
  'methodology': None,
  'methodology_references': [{'source': None, 'uri': '', 'note': None}],
  'derivation': None,
  'derivation_references': [{'source': None, 'uri': '', 'note': None}],
  'imputation': None,
  'imputation_references': [{'source': None, 'uri': '', 'note': None}],
  'seasonal_adjustment': None,
  'adjustments': [],
  'missing': None,
  'validation_rules': [],
  'quality_checks': None,
  'quality_note': None,
  'sources_discrepancies': None,
  'series_break': None,
  'limitation': None,
  'themes': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'topics': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'disciplines': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'relevance': None,
  'mandate': {'mandate': None, 'uri': None},
  'time_periods': [{'start': None, 'end': None, 'notes': None}],
  'ref_country': [{'name': None, 'code': None}],
  'geographic_units': [{'name': '', 'code': None, 'type': None}],
  'bbox': [{'west': None, 'east': None, 'south': None, 'north': None}],
  'aggregation_method': None,
  'aggregation_method_references': [{'source': None, 'uri': '', 'note': None}],
  'disaggregation': None,
  'license': [{'name': None, 'uri': None, 'note': None}],
  'confidentiality': None,
  'confidentiality_status': None,
  'confidentiality_note': None,
  'citation_requirement': None,
  'links': [{'type': None, 'description': None, 'uri': None}],
  'api_documentation': [{'description': None, 'uri': None}],
  'sources': [{'idno': None,
    'other_identifiers': [{'type': None, 'identifier': None}],
    'type': None,
    'name': '',
    'organization': None,
    'authors': [{'first_name': None,
      'initial': None,
      'last_name': None,
      'affiliation': None,
      'author_id': [{'type': None, 'id': None}],
      'full_name': None}],
    'datasets': [{'idno': None, 'title': None, 'uri': None}],
    'publisher': None,
    'publication_date': None,
    'uri': None,
    'access_date': None,
    'note': None}],
  'sources_note': None,
  'direct_sources': [{'name': None,
    'organization': None,
    'uri': None,
    'note': None}],
  'keywords': [{'name': '', 'vocabulary': None, 'uri': None}],
  'acronyms': [{'acronym': '', 'expansion': '', 'occurrence': None}],
  'errata': [{'date': None, 'description': None, 'uri': None}],
  'acknowledgements': [{'name': None, 'affiliation': None, 'role': None}],
  'acknowledgement_statement': None,
  'disclaimer': None,
  'notes': [{'note': None, 'type': None, 'uri': None}],
  'related_indicators': [{'code': None,
    'label': None,
    'uri': None,
    'relationship': None,
    'type': None}],
  'compliance': [{'standard': '',
    'abbreviation': None,
    'custodian': None,
    'uri': None}],
  'framework': [{'name': '',
    'abbreviation': None,
    'custodian': None,
    'description': None,
    'goal_id': None,
    'goal_name': None,
    'goal_description': None,
    'target_id': None,
    'target_name': None,
    'target_description': None,
    'indicator_id': None,
    'indicator_name': None,
    'indicator_description': None,
    'uri': None,
    'notes': None}],
  'series_groups': [{'name': None,
    'description': None,
    'version': None,
    'uri': None}],
  'contacts': [{'name': None,
    'role': None,
    'position': None,
    'affiliation': None,
    'email': None,
    'telephone': None,
    'uri': None}]},
 'data_structure': [{'name': None,
   'label': None,
   'description': None,
   'data_type': None,
   'column_type': None,
   'time_period_format': None,
   'code_list': [{'code': None, 'name': None, 'description': None}],
   'code_list_reference': {'id': None,
    'name': None,
    'version': None,
    'uri': '',
    'note': None}}],
 'data_notes': [{'filters': [{'field': None, 'operator': None, 'value': []}],
   'note': None}],
 'datacite': {'doi': None,
  'prefix': None,
  'suffix': None,
  'creators': [{'name': '',
    'nameType': None,
    'givenName': None,
    'familyName': None}],
  'titles': [{'title': '', 'titleType': None, 'lang': None}],
  'publisher': None,
  'publicationYear': None,
  'types': {'resourceType': '', 'resourceTypeGeneral': None},
  'url': None,
  'language': None},
 'provenance': [{'origin_description': {'harvest_date': None,
    'altered': None,
    'base_url': None,
    'identifier': None,
    'date_stamp': None,
    'metadata_namespace': None}}],
 'tags': [{'tag': None, 'tag_group': None}],
 'additional': {'': ''}}

Pydantic is a nice python library for defining and validating data schemas. An outline for the timeseries schema can be created like so:

In [13]:
timeseries_pydantic = me.outline_metadata('timeseries', 'pydantic')
timeseries_pydantic

TimeseriesSchema(idno=None, metadata_information=MetadataInformation(title=None, idno=None, producers=[Producer(name=None, abbr=None, affiliation=None, role=None)], prod_date=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None)), series_description=SeriesDescription(idno='', doi=None, name='', display_name=None, authoring_entity=[AuthoringEntityItem(name='', affiliation=None, abbreviation='', email='', uri=None)], database_id=None, database_name=None, date_last_update=None, date_released=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None), aliases=[Alias(alias=None)], alternate_identifiers=[AlternateIdentifier(identifier='', name=None, database=None, uri=None, notes=None)], languages=[Language(name=None, code=None)], measurement_unit=None, power_code=None, dimensions=[Dimension(name=None, label='', description=None)], release_calendar=None, periodicity=None, base_period=None, definition_short=None, definition_long=None, definition_references=[DefinitionReference(source=None, uri='', note=None)], statistical_concept=None, statistical_concept_references=[StatisticalConceptReference(source=None, uri='', note=None)], concepts=[Concept(name='', definition=None, uri=None)], universe=None, data_collection=DataCollection(data_source=None, method=None, period=None, note=None, uri=None), methodology=None, methodology_references=[MethodologyReference(source=None, uri='', note=None)], derivation=None, derivation_references=[DerivationReference(source=None, uri='', note=None)], imputation=None, imputation_references=[ImputationReference(source=None, uri='', note=None)], seasonal_adjustment=None, adjustments=[], missing=None, validation_rules=[], quality_checks=None, quality_note=None, sources_discrepancies=None, series_break=None, limitation=None, themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)], topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)], relevance=None, mandate=Mandate(mandate=None, uri=None), time_periods=[TimePeriod(start=None, end=None, notes=None)], ref_country=[RefCountryItem(name=None, code=None)], geographic_units=[GeographicUnit(name='', code=None, type=None)], bbox=[BboxItem(west=None, east=None, south=None, north=None)], aggregation_method=None, aggregation_method_references=[AggregationMethodReference(source=None, uri='', note=None)], disaggregation=None, license=[LicenseItem(name=None, uri=None, note=None)], confidentiality=None, confidentiality_status=None, confidentiality_note=None, citation_requirement=None, links=[Link(type=None, description=None, uri=None)], api_documentation=[ApiDocumentationItem(description=None, uri=None)], sources=[Source(idno=None, other_identifiers=[OtherIdentifier(type=None, identifier=None)], type=None, name='', organization=None, authors=[Author(first_name=None, initial=None, last_name=None, affiliation=None, author_id=[AuthorIdItem(type=None, id=None)], full_name=None)], datasets=[Dataset(idno=None, title=None, uri=None)], publisher=None, publication_date=None, uri=None, access_date=None, note=None)], sources_note=None, direct_sources=[DirectSource(name=None, organization=None, uri=None, note=None)], keywords=[Keyword(name='', vocabulary=None, uri=None)], acronyms=[Acronym(acronym='', expansion='', occurrence=None)], errata=[Erratum(date=None, description=None, uri=None)], acknowledgements=[Acknowledgement(name=None, affiliation=None, role=None)], acknowledgement_statement=None, disclaimer=None, notes=[Note(note=None, type=None, uri=None)], related_indicators=[RelatedIndicator(code=None, label=None, uri=None, relationship=None, type=None)], compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)], framework=[FrameworkItem(name='', abbreviation=None, custodian=None, description=None, goal_id=None, goal_name=None, goal_description=None, target_id=None, target_name=None, target_description=None, indicator_id=None, indicator_name=None, indicator_description=None, uri=None, notes=None)], series_groups=[SeriesGroup(name=None, description=None, version=None, uri=None)], contacts=[Contact(name=None, role=None, position=None, affiliation=None, email=None, telephone=None, uri=None)]), data_structure=[DataStructureItem(name=None, label=None, description=None, data_type=None, column_type=None, time_period_format=None, code_list=[CodeListItem(code=None, name=None, description=None)], code_list_reference=CodeListReference(id=None, name=None, version=None, uri='', note=None))], data_notes=[DataNote(filters=[Filter(field=None, operator=None, value=[])], note=None)], datacite=DataciteSchema(doi=None, prefix=None, suffix=None, creators=[Creator(name='', nameType=None, givenName=None, familyName=None)], titles=[Title(title='', titleType=None, lang=None)], publisher=None, publicationYear=None, types=Types(resourceType='', resourceTypeGeneral=None), url=None, language=None), provenance=[ProvenanceSchema(origin_description=OriginDescription(harvest_date=None, altered=None, base_url=None, identifier=None, date_stamp=None, metadata_namespace=None))], tags=[Tag(tag=None, tag_group=None)], additional={'': ''})

It can be updated using dot notation, for example:

In [14]:
timeseries_pydantic.metadata_information.producers[0].name = "example_producer"
timeseries_pydantic

TimeseriesSchema(idno=None, metadata_information=MetadataInformation(title=None, idno=None, producers=[Producer(name='example_producer', abbr=None, affiliation=None, role=None)], prod_date=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None)), series_description=SeriesDescription(idno='', doi=None, name='', display_name=None, authoring_entity=[AuthoringEntityItem(name='', affiliation=None, abbreviation='', email='', uri=None)], database_id=None, database_name=None, date_last_update=None, date_released=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None), aliases=[Alias(alias=None)], alternate_identifiers=[AlternateIdentifier(identifier='', name=None, database=None, uri=None, notes=None)], languages=[Language(name=None, code=None)], measurement_unit=None, power_code=None, dimensions=[Dimension(name=None, label='', description=None)], release_calendar=None, periodicity=None, base_period=None, definition_short=None, definition_long=None, definition_references=[DefinitionReference(source=None, uri='', note=None)], statistical_concept=None, statistical_concept_references=[StatisticalConceptReference(source=None, uri='', note=None)], concepts=[Concept(name='', definition=None, uri=None)], universe=None, data_collection=DataCollection(data_source=None, method=None, period=None, note=None, uri=None), methodology=None, methodology_references=[MethodologyReference(source=None, uri='', note=None)], derivation=None, derivation_references=[DerivationReference(source=None, uri='', note=None)], imputation=None, imputation_references=[ImputationReference(source=None, uri='', note=None)], seasonal_adjustment=None, adjustments=[], missing=None, validation_rules=[], quality_checks=None, quality_note=None, sources_discrepancies=None, series_break=None, limitation=None, themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)], topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)], relevance=None, mandate=Mandate(mandate=None, uri=None), time_periods=[TimePeriod(start=None, end=None, notes=None)], ref_country=[RefCountryItem(name=None, code=None)], geographic_units=[GeographicUnit(name='', code=None, type=None)], bbox=[BboxItem(west=None, east=None, south=None, north=None)], aggregation_method=None, aggregation_method_references=[AggregationMethodReference(source=None, uri='', note=None)], disaggregation=None, license=[LicenseItem(name=None, uri=None, note=None)], confidentiality=None, confidentiality_status=None, confidentiality_note=None, citation_requirement=None, links=[Link(type=None, description=None, uri=None)], api_documentation=[ApiDocumentationItem(description=None, uri=None)], sources=[Source(idno=None, other_identifiers=[OtherIdentifier(type=None, identifier=None)], type=None, name='', organization=None, authors=[Author(first_name=None, initial=None, last_name=None, affiliation=None, author_id=[AuthorIdItem(type=None, id=None)], full_name=None)], datasets=[Dataset(idno=None, title=None, uri=None)], publisher=None, publication_date=None, uri=None, access_date=None, note=None)], sources_note=None, direct_sources=[DirectSource(name=None, organization=None, uri=None, note=None)], keywords=[Keyword(name='', vocabulary=None, uri=None)], acronyms=[Acronym(acronym='', expansion='', occurrence=None)], errata=[Erratum(date=None, description=None, uri=None)], acknowledgements=[Acknowledgement(name=None, affiliation=None, role=None)], acknowledgement_statement=None, disclaimer=None, notes=[Note(note=None, type=None, uri=None)], related_indicators=[RelatedIndicator(code=None, label=None, uri=None, relationship=None, type=None)], compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)], framework=[FrameworkItem(name='', abbreviation=None, custodian=None, description=None, goal_id=None, goal_name=None, goal_description=None, target_id=None, target_name=None, target_description=None, indicator_id=None, indicator_name=None, indicator_description=None, uri=None, notes=None)], series_groups=[SeriesGroup(name=None, description=None, version=None, uri=None)], contacts=[Contact(name=None, role=None, position=None, affiliation=None, email=None, telephone=None, uri=None)]), data_structure=[DataStructureItem(name=None, label=None, description=None, data_type=None, column_type=None, time_period_format=None, code_list=[CodeListItem(code=None, name=None, description=None)], code_list_reference=CodeListReference(id=None, name=None, version=None, uri='', note=None))], data_notes=[DataNote(filters=[Filter(field=None, operator=None, value=[])], note=None)], datacite=DataciteSchema(doi=None, prefix=None, suffix=None, creators=[Creator(name='', nameType=None, givenName=None, familyName=None)], titles=[Title(title='', titleType=None, lang=None)], publisher=None, publicationYear=None, types=Types(resourceType='', resourceTypeGeneral=None), url=None, language=None), provenance=[ProvenanceSchema(origin_description=OriginDescription(harvest_date=None, altered=None, base_url=None, identifier=None, date_stamp=None, metadata_namespace=None))], tags=[Tag(tag=None, tag_group=None)], additional={'': ''})

The metadata editor also contains a nice helper function for printing metadata dictionaries and pydantic objects:

In [15]:
me.print_metadata(timeseries_pydantic)

{
  "idno": null,
  "metadata_information": {
    "title": null,
    "idno": null,
    "producers": [
      {
        "name": "example_producer",
        "abbr": null,
        "affiliation": null,
        "role": null
      }
    ],
    "prod_date": null,
    "version_statement": {
      "version": null,
      "version_date": null,
      "version_resp": null,
      "version_notes": null
    }
  },
  "series_description": {
    "idno": "",
    "doi": null,
    "name": "",
    "display_name": null,
    "authoring_entity": [
      {
        "name": "",
        "affiliation": null,
        "abbreviation": "",
        "email": "",
        "uri": null
      }
    ],
    "database_id": null,
    "database_name": null,
    "date_last_update": null,
    "date_released": null,
    "version_statement": {
      "version": null,
      "version_date": null,
      "version_resp": null,
      "version_notes": null
    },
    "aliases": [
      {
        "alias": null
      }
    ],
    "alternate_identifiers": [
      {
        "identifier": "",
        "name": null,
        "database": null,
        "uri": null,
        "notes": null
      }
    ],
    "languages": [
      {
        "name": null,
        "code": null
      }
    ],
    "measurement_unit": null,
    "power_code": null,
    "dimensions": [
      {
        "name": null,
        "label": "",
        "description": null
      }
    ],
    "release_calendar": null,
    "periodicity": null,
    "base_period": null,
    "definition_short": null,
    "definition_long": null,
    "definition_references": [
      {
        "source": null,
        "uri": "",
        "note": null
      }
    ],
    "statistical_concept": null,
    "statistical_concept_references": [
      {
        "source": null,
        "uri": "",
        "note": null
      }
    ],
    "concepts": [
      {
        "name": "",
        "definition": null,
        "uri": null
      }
    ],
    "universe": null,
    "data_collection": {
      "data_source": null,
      "method": null,
      "period": null,
      "note": null,
      "uri": null
    },
    "methodology": null,
    "methodology_references": [
      {
        "source": null,
        "uri": "",
        "note": null
      }
    ],
    "derivation": null,
    "derivation_references": [
      {
        "source": null,
        "uri": "",
        "note": null
      }
    ],
    "imputation": null,
    "imputation_references": [
      {
        "source": null,
        "uri": "",
        "note": null
      }
    ],
    "seasonal_adjustment": null,
    "adjustments": [],
    "missing": null,
    "validation_rules": [],
    "quality_checks": null,
    "quality_note": null,
    "sources_discrepancies": null,
    "series_break": null,
    "limitation": null,
    "themes": [
      {
        "id": null,
        "name": "",
        "parent_id": null,
        "vocabulary": null,
        "uri": null
      }
    ],
    "topics": [
      {
        "id": null,
        "name": "",
        "parent_id": null,
        "vocabulary": null,
        "uri": null
      }
    ],
    "disciplines": [
      {
        "id": null,
        "name": "",
        "parent_id": null,
        "vocabulary": null,
        "uri": null
      }
    ],
    "relevance": null,
    "mandate": {
      "mandate": null,
      "uri": null
    },
    "time_periods": [
      {
        "start": null,
        "end": null,
        "notes": null
      }
    ],
    "ref_country": [
      {
        "name": null,
        "code": null
      }
    ],
    "geographic_units": [
      {
        "name": "",
        "code": null,
        "type": null
      }
    ],
    "bbox": [
      {
        "west": null,
        "east": null,
        "south": null,
        "north": null
      }
    ],
    "aggregation_method": null,
    "aggregation_method_references": [
      {
        "source": null,
        "uri": "",
        "note": null
      }
    ],
    "disaggregation": null,
    "license": [
      {
        "name": null,
        "uri": null,
        "note": null
      }
    ],
    "confidentiality": null,
    "confidentiality_status": null,
    "confidentiality_note": null,
    "citation_requirement": null,
    "links": [
      {
        "type": null,
        "description": null,
        "uri": null
      }
    ],
    "api_documentation": [
      {
        "description": null,
        "uri": null
      }
    ],
    "sources": [
      {
        "idno": null,
        "other_identifiers": [
          {
            "type": null,
            "identifier": null
          }
        ],
        "type": null,
        "name": "",
        "organization": null,
        "authors": [
          {
            "first_name": null,
            "initial": null,
            "last_name": null,
            "affiliation": null,
            "author_id": [
              {
                "type": null,
                "id": null
              }
            ],
            "full_name": null
          }
        ],
        "datasets": [
          {
            "idno": null,
            "title": null,
            "uri": null
          }
        ],
        "publisher": null,
        "publication_date": null,
        "uri": null,
        "access_date": null,
        "note": null
      }
    ],
    "sources_note": null,
    "direct_sources": [
      {
        "name": null,
        "organization": null,
        "uri": null,
        "note": null
      }
    ],
    "keywords": [
      {
        "name": "",
        "vocabulary": null,
        "uri": null
      }
    ],
    "acronyms": [
      {
        "acronym": "",
        "expansion": "",
        "occurrence": null
      }
    ],
    "errata": [
      {
        "date": null,
        "description": null,
        "uri": null
      }
    ],
    "acknowledgements": [
      {
        "name": null,
        "affiliation": null,
        "role": null
      }
    ],
    "acknowledgement_statement": null,
    "disclaimer": null,
    "notes": [
      {
        "note": null,
        "type": null,
        "uri": null
      }
    ],
    "related_indicators": [
      {
        "code": null,
        "label": null,
        "uri": null,
        "relationship": null,
        "type": null
      }
    ],
    "compliance": [
      {
        "standard": "",
        "abbreviation": null,
        "custodian": null,
        "uri": null
      }
    ],
    "framework": [
      {
        "name": "",
        "abbreviation": null,
        "custodian": null,
        "description": null,
        "goal_id": null,
        "goal_name": null,
        "goal_description": null,
        "target_id": null,
        "target_name": null,
        "target_description": null,
        "indicator_id": null,
        "indicator_name": null,
        "indicator_description": null,
        "uri": null,
        "notes": null
      }
    ],
    "series_groups": [
      {
        "name": null,
        "description": null,
        "version": null,
        "uri": null
      }
    ],
    "contacts": [
      {
        "name": null,
        "role": null,
        "position": null,
        "affiliation": null,
        "email": null,
        "telephone": null,
        "uri": null
      }
    ]
  },
  "data_structure": [
    {
      "name": null,
      "label": null,
      "description": null,
      "data_type": null,
      "column_type": null,
      "time_period_format": null,
      "code_list": [
        {
          "code": null,
          "name": null,
          "description": null
        }
      ],
      "code_list_reference": {
        "id": null,
        "name": null,
        "version": null,
        "uri": "",
        "note": null
      }
    }
  ],
  "data_notes": [
    {
      "filters": [
        {
          "field": null,
          "operator": null,
          "value": []
        }
      ],
      "note": null
    }
  ],
  "datacite": {
    "doi": null,
    "prefix": null,
    "suffix": null,
    "creators": [
      {
        "name": "",
        "nameType": null,
        "givenName": null,
        "familyName": null
      }
    ],
    "titles": [
      {
        "title": "",
        "titleType": null,
        "lang": null
      }
    ],
    "publisher": null,
    "publicationYear": null,
    "types": {
      "resourceType": "",
      "resourceTypeGeneral": null
    },
    "url": null,
    "language": null
  },
  "provenance": [
    {
      "origin_description": {
        "harvest_date": null,
        "altered": null,
        "base_url": null,
        "identifier": null,
        "date_stamp": null,
        "metadata_namespace": null
      }
    }
  ],
  "tags": [
    {
      "tag": null,
      "tag_group": null
    }
  ],
  "additional": {
    "": ""
  }
}

Finally, a nicely formatted Excel file can be created into which the metadata can be written:

In [16]:
me.outline_metadata('timeseries', 'excel')

'timeseries_metadata.xlsx'

## Retreiving existing metadata

Likewise, existing projects can be downloaded as either dictionaries, pydantic models or as excel spreadsheets.

In [4]:
demo_dict = me.get_project_metadata_by_id(timeseries_id, mode='dict')
demo_dict

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

{'idno': 'GB20240708_demo1',
 'series_description': {'idno': 'GB20240708_demo1',
  'doi': 'V1',
  'name': 'Version 1',
  'display_name': 'Version 1'}}

In [5]:
demo_pydantic = me.get_project_metadata_by_id(timeseries_id, mode='pydantic')
demo_pydantic

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

TimeseriesSchema(idno='GB20240708_demo1', metadata_information=MetadataInformation(title=None, idno=None, producers=[Producer(name=None, abbr=None, affiliation=None, role=None)], prod_date=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None)), series_description={'idno': 'GB20240708_demo1', 'doi': 'V1', 'name': 'Version 1', 'display_name': 'Version 1'}, data_structure=[DataStructureItem(name=None, label=None, description=None, data_type=None, column_type=None, time_period_format=None, code_list=[CodeListItem(code=None, name=None, description=None)], code_list_reference=CodeListReference(id=None, name=None, version=None, uri='', note=None))], data_notes=[DataNote(filters=[Filter(field=None, operator=None, value=[])], note=None)], datacite=DataciteSchema(doi=None, prefix=None, suffix=None, creators=[Creator(name='', nameType=None, givenName=None, familyName=None)], titles=[Title(title='', titleType=None, lang=None)], publisher=None, publicationYear=None, types=Types(resourceType='', resourceTypeGeneral=None), url=None, language=None), provenance=[ProvenanceSchema(origin_description=OriginDescription(harvest_date=None, altered=None, base_url=None, identifier=None, date_stamp=None, metadata_namespace=None))], tags=[Tag(tag=None, tag_group=None)], additional={'': ''})

In [7]:
me.get_project_metadata_by_id(timeseries_id, mode='excel', filename='GB20240708_demo1.xlsx')

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

'GB20240708_demo1.xlsx'

### Updating an existing project

You can create and update projects with metadata as either dictionaries, pydantic models or in Excel files.

In [8]:
demo_pydantic.metadata_information.producers[0].name = "example_producer"
me.update_project_log_by_id(timeseries_id, demo_pydantic)

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [4]:
me.get_project_metadata_by_id(timeseries_id, 'pydantic')

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

TimeseriesSchema(idno='GB20240708_demo1', metadata_information=MetadataInformation(title=None, idno=None, producers=[Producer(name='example_producer', abbr=None, affiliation=None, role=None)], prod_date=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None)), series_description=SeriesDescription(idno='GB20240708_demo1', doi='V1', name='Version 1', display_name='Version 1', authoring_entity=[AuthoringEntityItem(name='', affiliation=None, abbreviation='', email='', uri=None)], database_id=None, database_name=None, date_last_update=None, date_released=None, version_statement=VersionStatement(version=None, version_date=None, version_resp=None, version_notes=None), aliases=[Alias(alias=None)], alternate_identifiers=[AlternateIdentifier(identifier='', name=None, database=None, uri=None, notes=None)], languages=[Language(name=None, code=None)], measurement_unit=None, power_code=None, dimensions=[Dimension(name=None, label='', description=None)], release_calendar=None, periodicity=None, base_period=None, definition_short=None, definition_long=None, definition_references=[DefinitionReference(source=None, uri='', note=None)], statistical_concept=None, statistical_concept_references=[StatisticalConceptReference(source=None, uri='', note=None)], concepts=[Concept(name='', definition=None, uri=None)], universe=None, data_collection=DataCollection(data_source=None, method=None, period=None, note=None, uri=None), methodology=None, methodology_references=[MethodologyReference(source=None, uri='', note=None)], derivation=None, derivation_references=[DerivationReference(source=None, uri='', note=None)], imputation=None, imputation_references=[ImputationReference(source=None, uri='', note=None)], seasonal_adjustment=None, adjustments=[], missing=None, validation_rules=[], quality_checks=None, quality_note=None, sources_discrepancies=None, series_break=None, limitation=None, themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)], topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)], relevance=None, mandate=Mandate(mandate=None, uri=None), time_periods=[TimePeriod(start=None, end=None, notes=None)], ref_country=[RefCountryItem(name=None, code=None)], geographic_units=[GeographicUnit(name='', code=None, type=None)], bbox=[BboxItem(west=None, east=None, south=None, north=None)], aggregation_method=None, aggregation_method_references=[AggregationMethodReference(source=None, uri='', note=None)], disaggregation=None, license=[LicenseItem(name=None, uri=None, note=None)], confidentiality=None, confidentiality_status=None, confidentiality_note=None, citation_requirement=None, links=[Link(type=None, description=None, uri=None)], api_documentation=[ApiDocumentationItem(description=None, uri=None)], sources=[Source(idno=None, other_identifiers=[OtherIdentifier(type=None, identifier=None)], type=None, name='', organization=None, authors=[Author(first_name=None, initial=None, last_name=None, affiliation=None, author_id=[AuthorIdItem(type=None, id=None)], full_name=None)], datasets=[Dataset(idno=None, title=None, uri=None)], publisher=None, publication_date=None, uri=None, access_date=None, note=None)], sources_note=None, direct_sources=[DirectSource(name=None, organization=None, uri=None, note=None)], keywords=[Keyword(name='', vocabulary=None, uri=None)], acronyms=[Acronym(acronym='', expansion='', occurrence=None)], errata=[Erratum(date=None, description=None, uri=None)], acknowledgements=[Acknowledgement(name=None, affiliation=None, role=None)], acknowledgement_statement=None, disclaimer=None, notes=[Note(note=None, type=None, uri=None)], related_indicators=[RelatedIndicator(code=None, label=None, uri=None, relationship=None, type=None)], compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)], framework=[FrameworkItem(name='', abbreviation=None, custodian=None, description=None, goal_id=None, goal_name=None, goal_description=None, target_id=None, target_name=None, target_description=None, indicator_id=None, indicator_name=None, indicator_description=None, uri=None, notes=None)], series_groups=[SeriesGroup(name=None, description=None, version=None, uri=None)], contacts=[Contact(name=None, role=None, position=None, affiliation=None, email=None, telephone=None, uri=None)]), data_structure=[DataStructureItem(name=None, label=None, description=None, data_type=None, column_type=None, time_period_format=None, code_list=[CodeListItem(code=None, name=None, description=None)], code_list_reference=CodeListReference(id=None, name=None, version=None, uri='', note=None))], data_notes=[DataNote(filters=[Filter(field=None, operator=None, value=[])], note=None)], datacite=DataciteSchema(doi=None, prefix=None, suffix=None, creators=[Creator(name='', nameType=None, givenName=None, familyName=None)], titles=[Title(title='', titleType=None, lang=None)], publisher=None, publicationYear=None, types=Types(resourceType='', resourceTypeGeneral=None), url=None, language=None), provenance=[ProvenanceSchema(origin_description=OriginDescription(harvest_date=None, altered=None, base_url=None, identifier=None, date_stamp=None, metadata_namespace=None))], tags=[Tag(tag=None, tag_group=None)], additional={'': ''})

In [6]:
me.get_project_metadata_by_id(timeseries_id, 'excel', filename='GB20240708_demo1_updated.xlsx')

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

'GB20240708_demo1_updated.xlsx'

# Collections

We can list and create collections, we can add and remove projects from collections and we can apply templates to collections.

In [5]:
me.list_collections().head()

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,title,description,created,changed,created_by,changed_by,pid,wgt,username
id,,,,,,,,,
8,aL-moved,Collection description Text,1970-01-01T00:33:43+00:00,2024-02-06T04:04:35+00:00,13,20,None,None,chriskrestel
18,CCKP,World Bank Climate Change Knowledge Platform,2024-06-05T02:04:21+00:00,2024-06-05T02:04:21+00:00,2,2,None,None,Olivier Dupriez
12,Emmanuel,None,2024-04-30T13:23:31+00:00,2024-04-30T13:23:31+00:00,2,2,None,None,Olivier Dupriez
20,geoflow,Projects published through geoflow (https://gi...,2024-06-11T19:35:48+00:00,2024-06-11T19:35:48+00:00,22,22,None,None,Emmanuel Blondel
11,Geospatial,None,2024-04-30T12:40:41+00:00,2024-04-30T12:40:41+00:00,1,1,None,None,admin admin

In [7]:
collection_id = me.create_collection("GB20240708_demo_collection", description = "An example collection for demonstration")

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [8]:
me.get_collection_by_id(collection_id)

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

id                                                  59
title                       GB20240708_demo_collection
description    An example collection for demonstration
created                                     1723059490
changed                                     1723059490
created_by                                          24
changed_by                                          24
pid                                               None
wgt                                               None
dtype: object

## Populating collections

In [9]:
me.add_projects_to_collection(collection=collection_id, id_format='id', projects=[timeseries_id])

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [10]:
me.list_projects_in_collection(collection_id)

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,published,created,changed,varcount,created_by,changed_by,is_shared,thumbnail,template_uid,username,username_cr,collections
id,,,,,,,,,,,,,,,,,,,,
2022,timeseries,GB20240708_demo1,GB20240708_demo1,Version 1,None,,0,0,None,2024-08-07T16:55:14+00:00,2024-08-07T18:20:40+00:00,None,24,24,None,None,8603d94e27bccc2bdad1e00dbbf0fe32en,Gordon Blackadder,Gordon Blackadder,"[{'id': '59', 'title': 'GB20240708_demo_collec..."

In [11]:
me.remove_projects_from_collection(collection=collection_id, id_format='id', projects=[timeseries_id])

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

## Deleting Collections

In [12]:
me.delete_collection_by_id(collection_id)

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

## Deleting Projects

In [19]:
me.delete_project_by_id(timeseries_id)

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

# Templates

In [3]:
me.list_templates().head()

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,uid,template_type,name,data_type,lang,template,default,id,version,organization,author,description,instructions,created,changed
0,microdata-system-en,core,Microdata DDI 2.5 EN,survey,en,metadata_editor/metadata_editor_templates/surv...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,232ea3aaece0cdf1db157f797f6b92e5fr,core,IHSN DDI 2.5 Modèle v01 FR,survey,fr,metadata_editor/metadata_editor_templates/surv...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6740f5f920502baf3f6cbcaa5c113deeen,core,IHSN DDI 2.5 Template v01 EN,survey,en,metadata_editor/metadata_editor_templates/surv...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,timeseries-system-en,core,Indicator Schema 1.0 EN,timeseries,en,metadata_editor/metadata_editor_templates/time...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8603d94e27bccc2bdad1e00dbbf0fe32en,core,IHSN INDICATOR 1.0 Template v01 EN,timeseries,en,metadata_editor/metadata_editor_templates/time...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
me.get_template_by_uid("microdata-system-en")

c:\Users\wb625523\sources\pyMetadataEditor\.venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

uid                                            microdata-system-en
template_type                                                 core
name                                          Microdata DDI 2.5 EN
data_type                                                   survey
lang                                                            en
template         {'type': 'template', 'title': 'Microdata Proje...
Name: Microdata DDI 2.5 EN, dtype: object

## Explanatory Error Messages

### When the URL is not secure

In [10]:
your_api_key = "bad key"
api_url = "http://example.org/index.php/api/"
me = MetadataEditor(api_url=api_url, api_key=your_api_key)

ValidationError: 1 validation error for MetadataEditor
api_url
  URL scheme should be 'https' [type=url_scheme, input_value='http://example.org/index.php/api/', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/url_scheme

### When the URL is wrong

In [11]:
your_api_key = "bad key"
api_url = "https://example.org/index.php/api/"
me = MetadataEditor(api_url=api_url, api_key=your_api_key)

HTTPError: Page not found. Try checking the URL.
Generally the required URL looks like 'https://<name_of_your_metadata_database>.org/index.php/api', but the URL that was passed was 'https://example.org/index.php/api/'

### When the api key is invalid

In [12]:
api_key = "bad_key"
me_bad = MetadataEditor(api_url="https://metadataeditorqa.worldbank.org/index.php/api",
                        api_key=api_key)
me_bad.list_projects()

PermissionError: Access to that URL is denied. Check that the API key 'bad_key' is correct

### When required data is missing or the type is incorred

In [13]:
series_description = {
                        "idno": 17,
                        "doi": "demoV1",
                     }

me.create_and_log_timeseries(idno="GB20240617_demo3",
                     series_description=series_description)

ValidationError: 2 validation errors for TimeseriesSchema
series_description.idno
  Input should be a valid string [type=string_type, input_value=17, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
series_description.name
  Field required [type=missing, input_value={'idno': 17, 'doi': 'demoV1'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

### When the id is incorrect

In [14]:
series_description= {
                "idno": "GB20240617_demo1",
                "doi": "V2",
                "name": "Version 2",
                "display_name": "Version 2",
                "authoring_entity": [{"name": "example agency"}]
                }

me.update_timeseries_by_id(1,
                           series_description=series_description)

PermissionError: Access to this id is denied. Check that the id '1' is correct